kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/acm-processor /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/acm-processor
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/adminapp-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/adminapp-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/adsync-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/adsync-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/airwatch-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/airwatch-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/alerts-processing-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/alerts-processing-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/antimalware-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/antimalware-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/app-control-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/app-control-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/assessment-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/assessment-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/asset-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/asset-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/asset-write-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/asset-write-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/aws-token-provider /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/aws-token-provider
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/binary-download-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/binary-download-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/binary-upload-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/binary-upload-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/cdm-adminapp-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/cdm-adminapp-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/client-application-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/client-application-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/cloud-adapter-aws-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/cloud-adapter-aws-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/cloud-adapter-azure-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/cloud-adapter-azure-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/common-command-processor /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/common-command-processor
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/common-command-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/common-command-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/common-command-spoc-processor /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/common-command-spoc-processor
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/common-inventory-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/common-inventory-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/common-policy-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/common-policy-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/common-workbench-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/common-workbench-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/configuration-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/configuration-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/connection-profile-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/connection-profile-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/csp-broker-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/csp-broker-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/cwp-ui-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/cwp-ui-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/demo-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/demo-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/device-control-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/device-control-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/device-integrity-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/device-integrity-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/discovery-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/discovery-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/dnd-ui-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/dnd-ui-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/endpoint-console-user-management-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/endpoint-console-user-management-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/enrollment-service-cp1 /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/enrollment-service-cp1
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/enrollment-service-sp1 /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/enrollment-service-sp1
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/event-ingestion-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/event-ingestion-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/exploit-mitigation-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/exploit-mitigation-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/file-insight-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/file-insight-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/firewall-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/firewall-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/flowable-integration-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/flowable-integration-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/gcs-proxy /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/gcs-proxy
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/hardening-backend-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/hardening-backend-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/hardening-frontend-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/hardening-frontend-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/hash-importing-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/hash-importing-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/hid-event-broker /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/hid-event-broker
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/icdm-policy-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/icdm-policy-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/idp-ui-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/idp-ui-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/inventory-query-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/inventory-query-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/licensing-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/licensing-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/mdr-aurora /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/mdr-aurora
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/mdr-v2-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/mdr-v2-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/mobile-inventory-broker-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/mobile-inventory-broker-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/network-ips-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/network-ips-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/networkintegrity-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/networkintegrity-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/notification-aggregator-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/notification-aggregator-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/opstate-assessment-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/opstate-assessment-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/opstate-ingestion-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/opstate-ingestion-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/policy-agent-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/policy-agent-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/policy-artifact-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/policy-artifact-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/portal-authorization-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/portal-authorization-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/rating-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/rating-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/reporting-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/reporting-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/routing-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/routing-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/saep-provisioning-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/saep-provisioning-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/scheduler-service-cp1 /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/scheduler-service-cp1
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/scheduler-service-sp1 /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/scheduler-service-sp1
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/sep-eg-upgrade-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/sep-eg-upgrade-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/sepm-bridge-feeder /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/sepm-bridge-feeder
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/sepm-bridge-feeder-aws /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/sepm-bridge-feeder-aws
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/sepm-bridge-reader /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/sepm-bridge-reader
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/ses-content-management-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/ses-content-management-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/ses-mdm-intune /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/ses-mdm-intune
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/ses-mobile-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/ses-mobile-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/sesc-sepm-orch-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/sesc-sepm-orch-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/shadow-data-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/shadow-data-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/shadow-walker-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/shadow-walker-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/software-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/software-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/um-ui-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/um-ui-service
kubectl cp demo-service-78c978c766-c5xrs:/usr/local/symantec/icdm/coverage/logs/user-query-service /Users/ab732698/Downloads/systemtests/UAT_Phase1/logs1/user-query-service