apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: icdm-system-tests-claims
  namespace: sedsep-ci
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: icdm-filestore-rwx
  resources:
    requests:
      storage: 1Ti